import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import {
  calculateTakerFee,
  decideTrade,
  evaluateLeadLag,
  parseTwapWindowSec,
} from '../src/core/research/strategy_evidence.mjs';
import {
  calculateRollingTwap,
  createScreenRun,
} from '../src/core/research/strategy_screen_storage.mjs';
import { parseChainlinkRtdsMessage, subscribeChainlinkPriceReports } from '../src/core/research/external_btc_market_data.mjs';
import { isFutureBinaryMarket, resolveBinaryTokens } from '../src/tools/polymarket_strategy_screen_collector.mjs';
import { generateStrategyScreenReport } from '../src/tools/polymarket_strategy_screen_report.mjs';
import { verifyStrategyEvidenceReport } from '../src/core/risk/strategy_evidence_guard.mjs';

test('parses an explicitly declared Chainlink TWAP window and rejects ambiguous rules', () => {
  assert.equal(
    parseTwapWindowSec('This market resolves using the 60 second TWAP generated by Chainlink.'),
    60,
  );
  assert.equal(
    parseTwapWindowSec('Chainlink BTC/USD TWAP data stream: https://data.chain.link/streams/btc-usd-twap-60s-streams'),
    60,
  );
  assert.equal(parseTwapWindowSec('This market resolves using Chainlink price data.'), null);
  assert.equal(parseTwapWindowSec('30 second TWAP and 60 second TWAP'), null);
});

test('uses the protocol taker-fee curve rather than a fixed percent of notional', () => {
  assert.equal(calculateTakerFee({ shares: 100, price: 0.5, feeRate: 0.07 }), 1.75);
  assert.equal(calculateTakerFee({ shares: 100, price: 0.1, feeRate: 0.07 }), 0.63);
});

test('does not trade when the displayed probability edge is consumed by executable spread and fees', () => {
  assert.deepEqual(
    decideTrade({
      yesFairProbability: 0.60,
      yesAsk: 0.59,
      yesBid: 0.57,
      noAsk: 0.43,
      noBid: 0.41,
      yesAskSize: 10,
      noAskSize: 10,
      minSize: 5,
      feeRate: 0.07,
      edgeBuffer: 0.001,
      secondsRemaining: 90,
    }),
    { action: 'hold', reason: 'edge_below_cost_buffer' },
  );
});

test('calculates a declared-window Chainlink TWAP by the duration each report was effective', () => {
  assert.equal(calculateRollingTwap({
    reports: [
      { timestamp: 1_000, value: 100 },
      { timestamp: 31_000, value: 106 },
      { timestamp: 61_000, value: 112 },
    ],
    nowMs: 61_000,
    windowSec: 60,
  }), 103);
  assert.equal(calculateRollingTwap({
    reports: [
      { timestamp: 31_000, value: 106 },
      { timestamp: 61_000, value: 112 },
    ],
    nowMs: 61_000,
    windowSec: 60,
  }), null);
  assert.equal(calculateRollingTwap({ reports: [], nowMs: 61_000, windowSec: 60 }), null);
  assert.equal(calculateRollingTwap({
    reports: [{ timestamp: 1_000, value: 100 }],
    nowMs: 61_000,
    windowSec: 60,
    maxReportAgeSec: 10,
  }), null);
});

test('refuses an existing run directory without changing its raw data', async () => {
  const root = await mkdtemp(join(tmpdir(), 'strategy-screen-'));
  const outputRoot = join(root, 'nested', 'screen-runs');
  const runId = '20260824T000000Z-test';
  const first = await createScreenRun({ outputRoot, runId, nowMs: 1 });
  await writeFile(first.rawPath, '{"fixture":true}\n');
  const original = await readFile(first.rawPath, 'utf8');
  await assert.rejects(() => createScreenRun({ outputRoot, runId, nowMs: 2 }), /run_directory_exists/);
  assert.equal(await readFile(first.rawPath, 'utf8'), original);
});

test('accepts only fresh BTC/USD Chainlink RTDS price reports', () => {
  assert.deepEqual(
    parseChainlinkRtdsMessage(JSON.stringify({
      topic: 'crypto_prices_chainlink',
      type: 'update',
      payload: { symbol: 'btc/usd', timestamp: 1234, value: 67890.12 },
    })),
    { timestamp: 1234, value: 67890.12 },
  );
  assert.equal(parseChainlinkRtdsMessage('{"topic":"crypto_prices","payload":{"symbol":"btc/usd","timestamp":1,"value":2}}'), null);
  assert.equal(parseChainlinkRtdsMessage('not-json'), null);
});

test('reconnects the Chainlink RTDS subscription after an unexpected close', () => {
  class FakeWebSocket {
    static instances = [];
    constructor(url) { this.url = url; this.sent = []; FakeWebSocket.instances.push(this); }
    send(message) { this.sent.push(message); }
    close() {}
  }
  const errors = [];
  const subscription = subscribeChainlinkPriceReports({
    WebSocketImpl: FakeWebSocket,
    onError: (reason) => errors.push(reason),
    setTimeoutImpl: (fn) => { fn(); return 1; },
    clearTimeoutImpl: () => {},
  });
  FakeWebSocket.instances[0].onopen();
  assert.ok(FakeWebSocket.instances[0].sent[0].includes('btc/usd'));
  FakeWebSocket.instances[0].onclose();
  assert.equal(FakeWebSocket.instances.length, 2);
  assert.deepEqual(errors, ['chainlink_rtds_closed']);
  subscription.close();
});

test('resolves both current Up/Down and legacy Yes/No binary market token labels', () => {
  assert.deepEqual(resolveBinaryTokens({
    outcomes: '["Up", "Down"]',
    clobTokenIds: '["up-token", "down-token"]',
  }), { yes: 'up-token', no: 'down-token' });
  assert.deepEqual(resolveBinaryTokens({
    outcomes: '["Yes", "No"]',
    clobTokenIds: '["yes-token", "no-token"]',
  }), { yes: 'yes-token', no: 'no-token' });
  assert.equal(resolveBinaryTokens({ outcomes: '["Up", "No"]', clobTokenIds: '["a", "b"]' }), null);
});

test('skips Gamma markets whose end time has already passed even when Gamma still marks them active', () => {
  const market = { closed: false, endDate: '2026-08-24T15:40:00Z', outcomes: '["Up", "Down"]', clobTokenIds: '["up", "down"]' };
  assert.equal(isFutureBinaryMarket(market, Date.parse('2026-08-24T15:40:00Z')), false);
  assert.equal(isFutureBinaryMarket(market, Date.parse('2026-08-24T15:39:59Z')), true);
});

test('requires a positive external-to-future-Polymarket relationship that vanishes when shuffled', () => {
  const aligned = [
    { external_return: 0.01, polymarket_forward_change: 0.02 },
    { external_return: -0.02, polymarket_forward_change: -0.03 },
    { external_return: 0.03, polymarket_forward_change: 0.04 },
  ];
  const shuffled = [
    { external_return: 0.01, polymarket_forward_change: -0.02 },
    { external_return: -0.02, polymarket_forward_change: 0.03 },
    { external_return: 0.03, polymarket_forward_change: -0.04 },
  ];
  assert.equal(evaluateLeadLag({ snapshots: aligned }).ok, true);
  assert.equal(evaluateLeadLag({ snapshots: shuffled }).ok, false);
});

test('report fails closed when the immutable raw file does not match its manifest', async () => {
  const runDir = await mkdtemp(join(tmpdir(), 'strategy-report-'));
  const raw = '{"valid":true}\n';
  await writeFile(join(runDir, 'raw.jsonl'), raw);
  await writeFile(join(runDir, 'manifest.json'), JSON.stringify({
    status: 'completed', run_id: 'fixture', raw_sha256: createHash('sha256').update('different').digest('hex'),
  }));
  await assert.rejects(() => generateStrategyScreenReport({ runDir }), /raw_sha256_mismatch/);
});

test('live evidence guard rejects a missing or non-eligible report', async () => {
  assert.deepEqual(await verifyStrategyEvidenceReport({ reportPath: '' }), { ok: false, reason: 'strategy_report_required' });
});
